;;; a68-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from a68-mode.el

(autoload 'a68-mode "a68-mode" "\
Major mode for editing Alogl68 files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.a68\\'" . a68-mode))
(register-definition-prefixes "a68-mode" '("a68-"))

;;; End of scraped data

(provide 'a68-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; a68-mode-autoloads.el ends here
