#import = [
		#"~/.config/alacritty/themes/themes/alacritty_0_12.toml"
#]

[env]
#TERM = "alacritty"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-l", "-c", "tmux a -t 0 || tmux -u"]
program = "/bin/zsh"

#it may works on xfwm4
[window]
#decorations = "Full"
opacity = 0.8
#startup_mode = "Maximized"
#dimensions = {columns = 50, lines = 50}
padding = {x = 10, y = 10}


#[keyboard]
#bindings = [
   #{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
#]
