#import = [
		#"~/.config/alacritty/themes/themes/alacritty_0_12.toml"
#]

# [font.normal]
# family = "MesloLGS NF"
# for powerline10k

[env]
#TERM = "alacritty"

[scrolling]
history = 10000
multiplier = 3

[shell]
# args = ["-l", "-c", "tmux a -t 0 || tmux -u"]
program = "/usr/bin/zsh"

#it may works on xfwm4
[window]
opacity = 0.8
#decorations = "Full"
#startup_mode = "Maximized"
#dimensions = {columns = 50, lines = 50}
padding = {x = 10, y = 10}


#[keyboard]
#bindings = [
   #{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
#]
